### ISSUE TITLE
Replace ScaleGestureDetector with own implementation

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gestures-android#15]
Capturing upstream [here](https://issuetracker.google.com/issues/37131665) that Google won't fix this issue. The issue is that when you execute a scale gesture and bring your fingures together, the scale gesture is aborted and onScaleEnd is called while you would expect it to execute longer.

![ezgif com-video-to-gif 45 45](https://user-images.githubusercontent.com/2151639/36312044-7d20fc7c-132d-11e8-90aa-d6a668a7c3ee.gif)

**Comment by LukasPaczos** [comment]
Another issue that should be resolved by our own implementation is quickzoom's deadzone.
![quickzoom deadzone](https://user-images.githubusercontent.com/16925074/37283514-9140f418-25f8-11e8-8ee3-430ec43d96f5.gif)
