### ISSUE TITLE
Accessing hidden field violation - ScaleGestureDetector

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gestures-android#39]
Refs. https://github.com/mapbox/mapbox-gl-native/issues/11625.
Android P introduces new restrictions when it comes to accessing `private` and `hidden` methods and fields within the SDK, see [the preview note](https://developer.android.com/preview/restrictions-non-sdk-interfaces.html).

https://github.com/mapbox/mapbox-gestures-android/pull/30 uses reflection to access private fields and we need to workaround that in preparation for the Android P release. 

There is already an issue tracked on the Google's [issue board](https://issuetracker.google.com/issues/37137502) regarding settable span values for the `ScaleGestureDetector`, I'm not really sure about chances of it being adressed.

/cc @tobrun

**Comment by LukasPaczos** [comment]
Noting here that since the release of the Android Pie, the hidden field access violation has been moved to the `light greylist`:
```
Accessing hidden field Landroid/view/View;->mAccessibilityDelegate:Landroid/view/View$AccessibilityDelegate; (light greylist, reflection)
```

**Comment by flavienbwk** [comment]
Problem is still active.

**Comment by LukasPaczos** [comment]
Noting that in the Android Q beta reflection on this particular part of the code has been moved to the "dark greylist":
```
Accessing hidden field Landroid/view/ScaleGestureDetector;->mMinSpan:I (greylist-max-p, reflection)
Accessing hidden field Landroid/view/ScaleGestureDetector;->mSpanSlop:I (greylist-max-p, reflection)
```
which based on [the docs](https://developer.android.com/preview/non-sdk-q):
> Similarly, if a greylisted non-SDK interface was not restricted in Android Pie but is now restricted in Android Q, that interface is part of the greylist-max-p list, where “p” stands for Pie or Android 9 (API level 28).

means that if the app targets Android Q or above, the workaround is going to result in no-op/exception.

Since there's no movement in [the ticket tracking the span in the scale gesture detector](https://issuetracker.google.com/issues/37137502), I think we're forced to roll out our own implementation by the time Android Q is officially released.
