### ISSUE TITLE
Failed to resolve: core

### ISSUE THREAD

**Issue by yasser9372** [mapbox/mapbox-gestures-android#63]
Hi. 
I am using androidX and i want to use a sdk witch use this lib with '0.3.0' version, but i get "Failed to resolve: core" error.
I also tried '0.4.0' version and received same error.

thanks.

**Comment by LukasPaczos** [comment]
Hey @yasser9372, thanks for reaching out!

I've created a new project with the AndroidX support enabled, added gestures library dependency and didn't run into any issues. Would you be able to provide your dependencies list, or a small project that visualizes the issue?

**Comment by tobrun** [comment]
androidX update has landed with #94
