### ISSUE TITLE
ERROR: Failed to resolve: com.mapbox.mapboxsdk:mapbox-android-gestures:0.6.0-SNAPSHOT

### ISSUE THREAD

**Issue by shakesgar** [mapbox/mapbox-gestures-android#91]
Hi,

Getting - ERROR: Failed to resolve: com.mapbox.mapboxsdk:mapbox-android-gestures:0.6.0-SNAPSHOT

Changing to 0.5.0 works fine.

**Comment by LukasPaczos** [comment]
Hey, are precisely following `SNAPSHOT` instructions from https://github.com/mapbox/mapbox-gestures-android#getting-started? I see the artifact showing up in the repository - http://oss.jfrog.org/oss-snapshot-local/com/mapbox/mapboxsdk/mapbox-android-gestures/0.6.0-SNAPSHOT/
